# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: build

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "ref: ${{ inputs.ref }}"

      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

        # You need to run `dagger project init` locally before and commit the cue.mod directory to the repository with its contents
      - name: Dagger
        uses: dagger/dagger-for-github@v2
        # See all options at https://github.com/dagger/dagger-for-github
        with:
          version: 0.2
          workdir: ./misc/dagger
          # To pin external dependencies, you can use `project update github.com/[package-source]@v[n]`
          cmds: |
            project update
            do build -l=debug --log-format=plain
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload out
        uses: actions/upload-artifact@v3
        with:
          name: out
          path: ./out/*
