name: push

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: ls -la

      - run: ls -la ./.github/workflows/

      - uses: "./.github/workflows/build.yaml"
        with:
          ref: ${{ github.ref }}
