name: push

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ndthanhdev/gotiny-cli/.github/workflows/build.yaml@develop
        with:
          ref: ${{ github.ref }}
