name: Release

on: push

jobs:
  build:
    name: Build

    strategy:
      matrix:
        os:
          - linux
          - darwin
          - windows
        arch:
          - amd64
          - 386
          - arm64
          - arm
        exclude:
          - os: windows
            arch: arm
          - os: darwin
            arch: arm
          - os: darwin
            arch: 386

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v2
        with:
          go-version: "~1.17.1"

      - name: Set bin name
        run: |
          echo "BIN_NAME=gotiny-${{matrix.os}}-${{matrix.arch}}" >> $GITHUB_ENV

      - name: Set bin extension
        if: ${{matrix.os == 'windows'}}
        run: |
          echo "BIN_NAME=${{env.BIN_NAME}}.exe" >> $GITHUB_ENV

      - name: Build
        run: |
          go build -o ./bin/${{env.BIN_NAME}}
        env:
          GOOS: ${{matrix.os}}
          GOARCH: ${{matrix.arch}}

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./bin/${{env.BIN_NAME}}
