name: Release

on:
  push:
    branches:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        os:
          - linux
          - darwin
          - windows
        arch:
          - amd64
          - 386
          - arm64
          - arm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: "~1.17.1"

      - name: Set bin name
        run: |
          echo "BIN_NAME=gotiny-${{matrix.os}}-${{matrix.arch}}" >> $GITHUB_ENV

      - name: Set bin extension
        if: ${{matrix.os == 'windows'}}
        run: |
          echo "BIN_NAME=${{env.BIN_NAME}}.exe" >> $GITHUB_ENV

      - run: |
          ls -la $GITHUB_WORKSPACE
      
      - run: |
          ls -la $GITHUB_WORKSPACE/bin

      - name: Build
        run: |
          go build GOOS=${{matrix.os}} GOARCH=${{matrix.arch}} -o $GITHUB_WORKSPACE/bin/${{env.BIN_NAME}}
