name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      ref: ${{ github.ref }}

  upload-bin:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          echo "version: ${{ needs.get_version.outputs.version }}"

      - uses: actions/download-artifact@v3
        with:
          name: out
          path: ./out

      - run: ls -la ./out

      - name: Upload out release artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: out
          files: ./out/*
