name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  get_version:
    name: Get version
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - id: get_version
        uses: battila7/get-version-action@v2

  build:
    needs:
      - get_version
    uses: ./.github/workflows/build.yaml
    with:
      ref: ${{ github.ref }}
      version: ${{ needs.get_version.outputs.version}}
      makeTar: true
      genFormula: true

  upload-bin:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          echo "version: ${{ needs.get_version.outputs.version }}"

      - uses: actions/download-artifact@v3
        with:
          name: out
          path: ./out

      - run: ls -la ./out

      - name: Upload out release artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: out
          files: ./out/*
