name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  upload: 
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "ref: ${{ github.ref }}"

      - uses: actions/checkout@v3

      # You need to run `dagger project init` locally before and commit the cue.mod directory to the repository with its contents
      - name: Dagger
        uses: dagger/dagger-for-github@v2
        # See all options at https://github.com/dagger/dagger-for-github
        with:
          version: 0.2
          workdir: ./misc/dagger
          # To pin external dependencies, you can use `project update github.com/[package-source]@v[n]`
          cmds: |
            project update
            do chocoPack -l=debug --log-format=plain

      - name: Upload out
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: out
          files: ./out/*

      - name: Upload out-choco
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: out-choco
          files: ./out-choco/*

  releaseToChocolatey:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "ref: ${{ github.ref }}"

      - uses: actions/checkout@v3

      # You need to run `dagger project init` locally before and commit the cue.mod directory to the repository with its contents
      - name: Dagger
        uses: dagger/dagger-for-github@v2
        # See all options at https://github.com/dagger/dagger-for-github
        with:
          version: 0.2
          workdir: ./misc/dagger
          # To pin external dependencies, you can use `project update github.com/[package-source]@v[n]`
          cmds: |
            project update
            do chocoPush -l=debug --log-format=plain
        env:
          CHOCO_TOKEN: ${{ secrets.CHOCO_TOKEN }}
