name: push

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: get_version
        uses: battila7/get-version-action@v2

      - uses: "./.github/workflows/build.yaml"
        with:
          ref: ${{ github.ref }}
          ver: ${{ steps.get_version.outputs.version }}

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./bin/*
